CREATE UNIQUE INDEX IF NOT EXISTS news_slug_unique ON public.news (slug);

INSERT INTO public.news (slug, title, excerpt, content, cover_url, category, author, published, published_at) VALUES
  ('padel-best-village-2026', 'BSG firma la nuova edizione di Padel Best Village 2026 a Roma EUR.', 'La seconda edizione del format esperienziale di BSG torna a maggio. Otto campi, area expo raddoppiata, otto sponsor main partner. Il villaggio del padel apre per dieci giorni a Roma EUR.', E'## Il format\n\nPadel Best Village torna a Roma EUR dal 16 al 26 maggio 2026 con la sua seconda edizione. Otto campi da gioco, un''area expo raddoppiata rispetto al 2025 e otto sponsor main partner che accompagneranno dieci giorni di sport, intrattenimento e brand experience.\n\n## Cosa cambia\n\n- Area expo da 1.200 mq\n- Palinsesto serale con DJ set e talk\n- Programma scuole con oltre 1.500 ragazzi coinvolti\n- Live streaming dei match clou sul network Padel Media\n\n## Le parole di BSG\n\n«Il padel è diventato un linguaggio universale: ci permette di connettere brand, persone e territorio in un formato che funziona dal vivo e si racconta benissimo sui canali social.» — Direzione BSG.', '/site/assets/imagery/case-quirino.jpg', 'Comunicato', 'Redazione BSG', true, '2026-05-04 09:00:00+00'::timestamptz),
  ('finstral-dooh-2026', 'Finstral × BSG: la finestra come elemento d''arredo, ora anche in DOOH.', 'La nuova campagna Finstral approda sui circuiti DOOH delle principali città italiane con un linguaggio visivo che racconta la finestra come oggetto di design.', E'La nuova campagna **Finstral** firmata BSG estende il claim "la finestra come elemento d''arredo" ai circuiti DOOH delle principali città italiane.\n\nPianificazione su Milano, Torino, Bologna e Roma, con creatività dinamiche calibrate sulla fascia oraria e sul meteo locale.', '/site/assets/imagery/case-finstral.jpg', 'Campagna', 'Redazione BSG', true, '2026-04-22 09:00:00+00'::timestamptz),
  ('stretching-marketing', 'Stretching marketing: come BSG estende il know-how ai format verticali.', 'Un editoriale sul metodo BSG di costruire format proprietari a partire dalle competenze media tradizionali.', E'Negli ultimi anni BSG ha costruito format verticali — Padel Best Village, Squisitus, Padel Media — partendo da un patrimonio di competenze media costruito in oltre trent''anni.\n\nQuesto editoriale racconta il metodo: come si passa dalla pianificazione all''ideazione di un format, e perché conviene.', null, 'Editoriale', 'Direzione BSG', true, '2026-04-11 09:00:00+00'::timestamptz),
  ('sole24ore-intervista-ooh', 'Intervista su Sole 24 Ore: «L''OOH è tornato dove appartiene, in mezzo alle persone».', 'L''intervista al direttore di BSG pubblicata sul Sole 24 Ore del 28 marzo 2026.', E'Il Sole 24 Ore ha pubblicato un''intervista alla direzione BSG sul ritorno dell''Out-Of-Home come medium centrale nelle pianificazioni multicanale.\n\n> «L''OOH è tornato dove appartiene: in mezzo alle persone, nei luoghi che frequentano davvero ogni giorno.»', null, 'Articolo stampa', 'Sole 24 Ore', true, '2026-03-28 09:00:00+00'::timestamptz),
  ('squisitus-2026-iscrizioni', 'Squisitus 2026: aperte le iscrizioni per produttori e brand del food.', 'Aperte le candidature per la nuova edizione del festival del gusto firmato BSG.', E'Squisitus torna nel 2026 con una nuova edizione dedicata ai produttori italiani d''eccellenza.\n\nLe iscrizioni per espositori, sponsor e media partner sono aperte fino al 30 settembre 2026.', null, 'Comunicato', 'Redazione BSG', true, '2026-03-14 09:00:00+00'::timestamptz),
  ('rds-primavera-ooh', 'RDS — palinsesto primavera: 4.2M di impression OOH stimate sull''area metropolitana.', 'I numeri della pianificazione OOH primavera 2026 per il network RDS.', E'La nuova pianificazione primavera 2026 per **RDS** prevede 4.2 milioni di impression stimate sull''area metropolitana di Roma e Milano, su una combinazione di formati statici e digitali.', '/site/assets/imagery/case-rds.jpg', 'Case in lancio', 'Redazione BSG', true, '2026-03-02 09:00:00+00'::timestamptz),
  ('eyes-tracking-percezione', 'Eyes tracking e psicologia della percezione: come decidiamo dove va un impianto.', 'Un editoriale tecnico sull''uso dei dati di eye-tracking nella scelta delle posizioni OOH.', E'Come si sceglie davvero la posizione di un impianto pubblicitario? L''editoriale racconta il metodo BSG basato su eye-tracking, flussi pedonali e analisi del contesto urbano.', null, 'Editoriale', 'Direzione BSG', true, '2026-02-14 09:00:00+00'::timestamptz),
  ('padel-media-debutto', 'Padel Media debutta: nasce il network editoriale del padel italiano.', 'Il nuovo network editoriale dedicato al padel italiano lanciato da BSG.', E'**Padel Media** è il nuovo network editoriale dedicato al padel italiano: una rete di canali digital, social e on-site che racconta il movimento attraverso news, highlight e live streaming.', null, 'Comunicato', 'Redazione BSG', true, '2026-01-28 09:00:00+00'::timestamptz)
ON CONFLICT (slug) DO NOTHING;